### ISSUE TITLE
`scrape_detail_page': undefined method `click' for nil:NilClass

### ISSUE THREAD

**Issue by tatey** [tatey/new-zealand-radio-spectrum-licenses#1]
```
/Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:56:in `scrape_detail_page': undefined method `click' for nil:NilClass (NoMethodError)
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:45:in `block in scrape_list_page'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:29:in `each'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:29:in `scrape_list_page'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:86:in `block (2 levels) in <top (required)>'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:85:in `loop'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:85:in `block in <top (required)>'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:83:in `each'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/scraper.rb:83:in `<top (required)>'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/bin/scrape:4:in `require_relative'
	from /Users/Tate/Code/tatey/new-zealand-television-transmitters-morphio-scraper/bin/scrape:4:in `<main>'
```

**Comment by tatey** [comment]
We were up to

```
I, [2017-01-17T22:09:19.469526 #41540]  INFO -- : Scraping search page for licence type VHF FM >=20 & <30dBW (Spectrum)
...
I, [2017-01-17T22:20:48.872792 #41540]  INFO -- : Scraping detail page for licence ID 108533
```

**Comment by tatey** [comment]
We're using Chrome now.
